apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: observai-autoinst
  namespace: observai-main
spec:
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  java:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:latest
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "http://apm-telemetry-collector.observability-otel.svc.cluster.local:4317"
      - name: OTEL_LOGS_EXPORTER
        value: otlp