kind: Elasticsearch
apiVersion: elasticsearch.k8s.elastic.co/v1
metadata:
  name: zaga-elasticsearch
  namespace: observability-redhat
spec:
  version: 8.12.0
  nodeSets:
    - name: default
      config:
        node.roles:
          - master
          - data
          - ingest
        node.attr.attr_name: attr_value
        node.store.allow_mmap: false
      podTemplate:
        metadata:
          labels:
            app: zaga-elasticsearch
        spec:
          containers:
            - name: elasticsearch
              resources:
                requests:
                  memory: 2Gi
                  cpu: 0.9
                limits:
                  memory: 3Gi
                  cpu: 1.2
      count: 1